"""followers

Revision ID: 411f679312cc
Revises: b0f0b4b24219
Create Date: 2020-11-05 12:00:28.461223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411f679312cc'
down_revision = 'b0f0b4b24219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
